//
// Created by andi on 29.03.2021.
//

#ifndef MCPWM_ARDUINO_PIN_DEF_H
#define MCPWM_ARDUINO_PIN_DEF_H

#include <esp_bit_defs.h>

#define DRAGRACE_PIN_LICHTSCHRANKE_L1_INPUT 23
#define DRAGRACE_PIN_LICHTSCHRANKE_L2_INPUT 19
#define DRAGRACE_PIN_LICHTSCHRANKE_L3_INPUT 22
#define DRAGRACE_PIN_LICHTSCHRANKE_R1_INPUT 32
#define DRAGRACE_PIN_LICHTSCHRANKE_R2_INPUT 33
#define DRAGRACE_PIN_LICHTSCHRANKE_R3_INPUT 25
#define DRAGRACE_PIN_TEST_L1_OUTPUT 17
#define DRAGRACE_PIN_TEST_L2_OUTPUT 2
#define DRAGRACE_PIN_TEST_L3_OUTPUT 5
//#define DRAGRACE_PIN_TEST_R1_OUTPUT
//#define DRAGRACE_PIN_TEST_R2_OUTPUT
//#define DRAGRACE_PIN_TEST_R3_OUTPUT
//#define DRAGRACE_PIN_HELTEC_LORA_DIO0
//#define DRAGRACE_PIN_HELTEC_LORA_DIO1
//#define DRAGRACE_PIN_HELTEC_LORA_DIO2
//#define DRAGRACE_PIN_HELTEC_LORA_MOSI
//#define DRAGRACE_PIN_HELTEC_LORA_MISO
//#define DRAGRACE_PIN_HELTEC_LORA_RST
//#define DRAGRACE_PIN_HELTEC_LORA_CS
//#define DRAGRACE_PIN_HELTEC_LORA_SCK
#define DRAGRACE_PIN_HELTEC_OLED_SCL 15
#define DRAGRACE_PIN_HELTEC_OLED_SDA 4
#define DRAGRACE_PIN_HELTEC_OLED_RST 16
#define DRAGRACE_PIN_HELTEC_VEXT 21



#endif //MCPWM_ARDUINO_PIN_DEF_H
